project/cliente/urls.py
from django.urls import path

from . import views

app_name = "cliente"

urlpatterns = [
    path("", views.home, name="index"),
    path("crearClientesVarios/", views.crearClientesVarios),
    path("busqueda/", views.busqueda),
    path("crear/", views.crear),
    path("/", views.crear),
]

project/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('cliente/', include("cliente.urls")),
    path('producto/', include("producto.urls")),
    
]

project/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.home, name="index" ),
    path('nosotros/', views.nosotros, name="nosotros"),
]

project/producto/urls.py
from django.urls import path
from . import views

app_name = "producto"

urlpatterns = [
    path('', views.home,name="index" ),
]

project/cliente/models.py
from django.db import models


class Pais(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    sexo = models.CharField(max_length=100)
    nacimiento = models.DateField(null=True, blank=True)
    pais_origen = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    


class Estudios(models.Model):
    estudios_cursados = models.CharField(max_length=50)

    def __str__(self):
        return f"Nivel {self.estudios_cursados}"

project/core/models.py
from django.db import models

# Create your models here.

project/producto/models.py
from django.db import models

# Create your models here.

project/cliente/forms.py
from django import forms
from . import models


class ClienteForm(forms.ModelForm):
    class Meta:
        model = models.Cliente
        fields = "__all__"

class ClienteBuscarForm(forms.ModelForm):
        sexo = forms.CharField()
        


class EstudioForm(forms.ModelForm):
    class Meta:
        model = models.Estudios
        fields = ["estudios_cursados"]

project/cliente/views.py
from datetime import date

from django.shortcuts import redirect, render
from . import models
from .forms import ClienteBuscarForm




def home(request):
    clientes = models.Cliente.objects.all()
    context = {"clientes": clientes}
    return render(request, "cliente/index.html", context)


def crearClientesVarios(request):
    p1 = models.Pais(nombre="Paraguay")
    p2 = models.Pais(nombre="México")
    p3 = models.Pais(nombre="Uruguay")
    p4 = models.Pais(nombre="Chile")
    p5 = models.Pais(nombre="Argentina")
    p1.save()
    p2.save()
    p3.save()
    p4.save()
    p5.save()
    c1 = models.Cliente(nombre="Almendra", apellido="Ruiseñor", sexo = "femenino" ,nacimiento=date(2015, 1, 1), pais_origen=p1)
    c2 = models.Cliente(nombre="Giordana", apellido="Tapello", sexo = "femenino", nacimiento=date(2005, 2, 2), pais_origen=p2)
    c3 = models.Cliente(nombre="Macarena", apellido="Lito", sexo = "femenino", nacimiento=date(1990, 1, 1), pais_origen=p3)
    c4 = models.Cliente(nombre="Jorge", apellido="Perez", sexo = "masculino", nacimiento=date(2005, 1, 1), pais_origen=None)
    c1.save()
    c2.save()
    c3.save()
    c4.save()
    return redirect("cliente:index")



def busqueda(request):
    # búsqueda por nombre que contenga "dana"
    cliente_nombre = models.Cliente.objects.filter(nombre__contains="dana")

    # nacimientos mayores a 2000
    cliente_nacimiento = models.Cliente.objects.filter(nacimiento__gt=date(2000, 1, 1))

    # país de origen vacío (null - None)
    cliente_pais = models.Cliente.objects.filter(pais_origen=None)
    
    cliente_sexo = models.Cliente.objects.filter(sexo= "masculino")

    context = {
        "cliente_nombre": cliente_nombre,
        "cliente_nacimiento": cliente_nacimiento,
        "cliente_pais": cliente_pais,
        "cliente_sexo": cliente_sexo,
    }
    return render(request, "cliente/busqueda.html", context)

def cliente_sexo_view(request):
    if request.method == "GET":
        form = ClienteBuscarForm()
        return render (request,"cliente/busqueda.html",context={"form":form})
    else:
        pass
 
from . import forms
from .forms import ClienteForm, EstudioForm 

def crear(request):
    if request.method == "POST":
        form_cliente = ClienteForm(request.POST)
        form_estudio = EstudioForm(request.POST)
        if form_cliente.is_valid() and form_estudio.is_valid():
            cliente = form_cliente.save()
            estudio = form_estudio.save(commit=False)
            estudio.cliente = cliente  # Asocia el cliente al estudio
            estudio.save()
            return redirect("cliente:index")  # Ajusta la ruta a la que deseas redirigir después de guardar
    else:
        form_cliente = ClienteForm()
        form_estudio = EstudioForm()

    return render(request, "cliente/crear.html", {"form_cliente": form_cliente, "form_estudio": form_estudio})

project/core/views.py
from django.shortcuts import render


# Create your views here.
def home (request):
    return render(request, "core/index.html")

def nosotros (request):
    return render(request, "core/nosotros.html")

project/producto/views.py
from django.shortcuts import render


# Create your views here.
def home (request):
    return render(request, "producto/index.html")

project/cliente/templates/cliente/busqueda.html
{% extends 'core/base.html' %}
    
{% block contenido_titulo %}
    BUSQUEDA  
{% endblock contenido_titulo %}


{% block contenido1 %}
    <h2>cliente nombre</h2>
    {% for cliente in cliente_nombre %}
        <p>{{cliente}}</p>
    
    {% endfor %}
{% endblock contenido1 %}    

    {% block contenido2 %}
    <h2>cliente Sexo</h2>
    {% for cliente in cliente_sexo %}
        <p>{{cliente}}</p>
    
    {% endfor %}
    
{% endblock contenido2 %}
    
<h2>cliente nacimiento</h2>
    {% for cliente in cliente_nacimiento %}
        <p>{{cliente}}</p>
    
    {% endfor %}
{% block contenido3 %}
    <h2>cliente Pais None</h2>
    {% for cliente in cliente_pais %}
        <p>{{cliente}}</p>
    
    {% endfor %}
{% endblock contenido3 %}

project/cliente/templates/cliente/crear.html
{% extends 'core/base.html' %}
    
{% block contenido_titulo %}
   CREAR  CLIENTE  
{% endblock contenido_titulo %}


{% block contenido %}
<form method="post">
    {% csrf_token %}
    {{ form_cliente.as_p }}
    {{ form_estudio.as_p }}
    <button type="submit">Guardar</button>

</form>


{% endblock contenido %}

project/cliente/templates/cliente/index.html
{% extends 'core/base.html' %}
    
{% block contenido_titulo %}
    CLIENTE  
{% endblock contenido_titulo %}


{% block contenido %}
    {% for cliente in clientes %}
       <h2>{{cliente.apellido}}</h2>
       <p>{{cliente.nombre}}</p>
       {% if  cliente.nacimiento %}
            <p>{{cliente.nacimiento}}</p>
       {% else %}
            <p>no esta registrado su fecha de naciemiento</p>
       {% endif %}
       {% if cliente.pais_origen %}
            <p>{{ cliente.pais_origen}}</p>
       {% else %}
            <p>no esta registrado su pais</p>
       {% endif %}
    {% endfor %}
{% endblock contenido %}

project/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>mi paginita</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'core/assets/favicon.ico' %}" /> 
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% include 'core/navbar.html' %}
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <h1>
                {% block contenido_titulo %}
        
                {% endblock contenido_titulo %}
            </h1>
            {% block contenido %}
        
            {% endblock contenido %}
            {% block contenido1 %}
        
            {% endblock contenido1 %}
            {% block contenido2 %}
        
            {% endblock contenido2 %}
            {% block contenido3 %}
        
            {% endblock contenido3 %}
             
        {% include 'core/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'core/js/scripts.js' %}"></script>
    </body>
</html>

project/core/templates/core/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{titulo}}</h2>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod tenetur ex natus at dolorem enim! Nesciunt pariatur voluptatem sunt quam eaque, vel, non in id dolore voluptates quos eligendi labore.</p>
        </div>
        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
    </div>
</div>

project/core/templates/core/footer.html
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Mi Paginita by gabyMen Copyright &copy; </p></div>
</footer>

project/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
    
{% block contenido_titulo %}
    CORE   
{% endblock contenido_titulo %}


{% block contenido %}
    <!-- Heading Row-->
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
        <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static 'core/img/indepte.jpg' %}" alt="..." /></div> 
        <div class="col-lg-5">
            <h1 class="font-weight-light">Business Name or Tagline</h1>
            <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
            <a class="btn btn-primary" href="#!">Call to Action!</a>
        </div>
    </div>
    <!-- Call to Action-->
    <div class="card text-white bg-secondary my-5 py-4 text-center">
        <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p></div>
    </div>
    <!-- Content Row-->
    <div class="row gx-4 gx-lg-5">
        {% include 'core/card.html' with titulo="Tarjeta 1" %}
        {% include 'core/card.html' with titulo="Tarjeta 2" %}
        {% include 'core/card.html' with titulo="Tarjeta 3" %}
        
    </div>
{% endblock contenido %}

    

project/core/templates/core/navbar.html
<!-- Responsive navbar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="#!">pagina con AppCoder</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:nosotros' %}">Nosotros</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'cliente:index' %}">Cliente</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'producto:index' %}">Producto</a></li>
            </ul>
        </div>
    </div>
</nav> 

project/core/templates/core/nosotros.html
{% extends 'core/base.html' %}

{% block contenido_titulo %}
    Nosotros
{% endblock contenido_titulo %}

{% block contenido %}
 <p>Esto es nosotros en mi paginita</p>   
{% endblock contenido %}

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}
    
{% block contenido_titulo %}
    PRODUCTO  
{% endblock contenido_titulo %}


{% block contenido %}
    <a href="{% url 'core:index' %}">volver al inicio</a>
{% endblock contenido %}